name: prince_of_pizza
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.3
  animated_splash: ^1.0.0
  cached_network_image: ^2.0.0
  fluttertoast: ^3.1.3

  # firebase
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.10.0
  cloud_firestore: ^0.12.5
  firebase_storage: ^3.1.1
  braintree_payment: ^1.2.3

  # Admin
  flutter_staggered_grid_view: ^0.3.0
  flutter_form_builder: ^3.8.1
  file_picker: ^1.4.3+2
  random_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
